from django.db import models
import datetime
from django.contrib.auth.models import User

PRODUCTOS = [
    "POLY TALLADO",
    "1.60 HEV TECH TALLA",
    "Ar 1.56 UV 400",
    "CR 39",
    "INV 70MM",
    "INV NEGATIVO",
    "PROG BLUE BALANCE 1.56",
    "PROG REA AR",
    "PROG REACH",
    "BISEL ESPECIAL",
    "BLUE BALANCE 1.60 F.RANGO",
    "BASE PROG SB NEXT AR TALLA",
    "PROG ISEE CR-39 TALLA",
    "SB NEXT",
    "1.56 BLUE BALANCE TALLA",
    "1.56 BLUE BALANCE F. RANGO",
    "1.56 HEV TECH",
    "1.56 HEV TECH F.RAN",
    "BASE PROG NEX TALLA",
    "FLAT TOP 70MM",
    "FLAT TOP NEGATIVO",
    "INVISIBLE BIFOCAL TALLA",
    "POLY HEV TECH",
    "POLY ANTIRREFLEJO",
    "POLY TINTABLE",
    "PROG CUTIE AR 12MM",
    "PROG REA AR NEGATIVO",
    "PROG REA NEGATIVO",
    "PROG SB NEXT AR",
    "SUNBALANCE AR NEXT",
    "BISEL CORRIENTE",
    "Bisel est",
    "BLUE FREE",
    "HEV TECH 1.60 F. RANGO",
    "PERFORACION",
    "POLY HEV TECH F. RAN",
    "FLAT TOP CR-39 TALLA",
    "POLY HEV TECH 2VC F. RANGO",
    "BISEL FREE",
    "BLUE BALANCE POLY TALLA",
    "FLAT TOP POLY TALLA",
    "POLY HEV TECH FILTRO AZUL TALLA",
    "Bise completo (FO-PR)",
    "Bisel completo especial",
    "BLUE SCREEN",
    "RANURACION",
    "INV POLY TER",
    "PROG BLUE BALANCE 1.56 NEGATIVO",
    "PROG CUTIE 12MM",
    "PROG SB NEXT AR NEGATIVO",
    "1.56 HEV TECH TALLA",
    "1.60 BLUE BALANCE TALLA",
    "CR TALLADO",
    "CR TRANS TALLADO",
    "NEOCHROMES CR BROWN TALLA",
    "POLY TRANS TALLADO",
    "POLY NO-VAP ANTI-NIEBLA",
    "AR SCREEN",
    "Bisel completo CR-39",
    "LOTO SCREEN",
    "PROG HEV TECH POLY",
    "FLAT TOP SB NEXT AR TALLA",
    "INVISIBLE SB NEXT AR TALLA",
    "Bisel ranura especial",
    "1.74 BASE BLUE BALANCE TALLA",
    "INVISIBLE SB NEXT TALLA",
    "SB NEXT TALLA",
    "Bisel perforac 3P esp (FO-PR)",
    "BISEL PERFORADO 3 P",
    "NUPOLAR GRIS",
    "PROG HEV TECH POLY NEGATIVO",
    "NEOCHROMES POLY TALLA",
    "NUPOLAR CAFÉ",
    "SUNBALANCE AR NEXT TALLA",
    "TRASPASO POR LENTE",
    "Bisel completo especial 2",
    "Bisel completo bifocal",
    "Articulo",
    "Bisel con perforacion 3P",
    "GRAPAS 3PCS",
    "PRISMAS",
    "FLAT TOP SB NEXT TALLA",
    "Bisel ranura bifocal",
    "Bisel ranura CR-39",
    "Bisel ranura especial (FO-PR)",
    "COLOR ESPECIAL",
    "COLOR FILTRO UV",
    "BLUE BALANCE ALTO INDICE 1.67 TALLA",
    "POLARIZADO CR CAFÉ TALLA",
    "POLARIZADO CR GRIS TALLA",
    "AR FREE",
    "Filtro UV",
    "Retiro de AR",
    "ALTO INDICE TALLA",
    "PROG CUTIE AR NEGATIVO",
    "NEOCHROMES CR TALLA",
    "AR PROMOCIONAL",
    "AR SMART PROM 1",
    "1.74 BASE SF TALLA",
    "FLAT TOP POLY TERM",
    "PELICULA ANTIRRAYAS",
    "LENTICULARIZACION",
    "PROG CUTIE NEGATIVO",
    "NEOCHROMES POLY BROWN TALLA",
    "NUPOLAR POLY GRIS TALLA",
    "NUPOLAR POLY VERDE TALLA",
    "POLARIZED XTRACTIVE TRANSITIONS TALLA",
    "POLARMAX POLY GRIS CURVA 8",
    "BISEL ESPECIAL COMPLETO C",
    "XTRACTIVE POLY GRAY TALLA",
    "Traspaso especial",
    "COLOR / FILTRO UV",
    "Pelicula antirayas",
    "POLARIZADO CR GRIS TALL",
    "POLARMAX POLY CAFE CURVA 6",
    "POLARMAX POLY GRIS CURVA 6",
    "KIT DE LIMPIEZA",
    "BISEL COMPLETO B POLY",
    "NUPOLAR POLY CAFÉ TALLA",
    "Antirreflejo Artech 2",
    "BISEL 3P especial MED",
    "BASE PROG ISEE POLY TALLA",
    "BASE DRIVEWEAR POLY TALLA",
    "BISEL RANURADO PO",
    "BISEL RANURA B. POLY",
    "PLAQUETA SILICONA",
    "bisel 3P espcecial MED",
    "AR SCREEN ZEN",
    "BLUE SCREEN ECX",
    "BLUE SCREEN ZEN",
    "Bisel Complet especial 2",
    "BISEL RANURA PO",
    "ESPEJADO ESPECIALES",
    "COLOR FILTRO UV",
    "POLARMAX POLY CAFE CURVA 8",
    "TRANSI SIGNAT GEN 8 POLY AR",
    "TRANSITIONS SIGNATURE GEN 8 POLY",
    "MAX UPGRADE MAX STEADY",
    "SERV TALLA MULTIFOCAL EXCILAB",
    "TRANSIT SIGNATURE GEN 8 CR-39",
    "Decoloracion - neutralizado",
    "DECOLORACION NEUTRALIZADO",
    "BLUE SCREEN IMEVI",
    "BLUE VISUALIZAMOS",
    "BLUE SCREEN BLACKFDAY",
    "NUPOLAR POLY GRADIENT CAFÉ TALLA",
    "NUPOLAR POLY GRADIENT GRIS TALLA",
    "VITA UPGRADE DELUXE",
    "DELUXE UPGRADE MAX",
    "MAX UPGRADE MAXMOBILE",
    "VITA UPGRADE DELUXE PRO",
    "DELUX UPGRADE DELUX PRO",
    "MAX MOBILE UPGRADE MAX STEADY",
    "Antirreflejo Artech LABORATORI",
    "AR KODAK",
    "Bisel Maxivision",
    "BLUE SCREEN EXCILAB",
    "BISEL VISUAL LENS",
    "BLUE SCREEN NEOCHROME PROMO",
    "BISEL ESPECIAL MEI",
    "NUPOLAR POLY GRADIENT CAFE GRIS TALLA",
    "BLUE SCREEN DIGITAL FRANQUI",
    "Decoloracion",
    "Pelicuala antirayas",
    "AR VISUALIZAMOS",
    "DELUXE UPGRADE MAX MOBILE",
    "AR SCREEN NEOCHROME PROMO",
    "BLUE SCREEN NEOCROME PROMO",
    "DELUXE PRO UPGRA MAX MOBILE",
    "MAX UPGRADE MAX MOBILE",
    "BLUE SCREEN ECXILAB",
    "HEV TECH POLY 2VC TALLA",
    "NUPOLAR CAFE",
    "POLARIZADO CR CAFE TALLA",
    "NUPOLAR POLY CAFE TALLA",
    "CAMBIO DE NARIGUERA",
    "Espejado"
]

PRODUCTOS.sort()

ESTADOS = ["Nuevo",
           "Proceso",
           "Contactado",
           "Laboratorio",
           "Trabajo"
]

SUCURSALES = ["Barranquilla",
           "Bucaramanga",
           "Cali",
           "Centro",
           "Chapinero",
           "Chía",
           "Cúcuta",
           "Deposito",
           "Manizales",
           "Medellín",
           "Neiva",
           "Olaya",
           "Pereira",
           "Pincipal",
           "PteAranda",
           "Rio Negro",
           "Tunja"
]
# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=10)
    empresa = models.CharField(max_length=100, null=True, blank=True)
    estado = models.CharField(max_length=32, choices=[(estado, estado) for estado in ESTADOS], blank=True)
    asesor = models.CharField(max_length=100, null=True, blank=True)
    # producto = models.CharField(max_length=255, choices=[(producto, producto) for producto in PRODUCTOS])
    producto = models.CharField(max_length=255)
    sucursal = models.CharField(max_length=32, choices=[(sucursal, sucursal) for sucursal in SUCURSALES], blank=True)
    fecha_in = models.DateField("Fecha de Ingreso", default=datetime.date.today)
    # fecha_sal = models.DateField("Fecha de Salida", default=datetime.date.today)
    observacion = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.nombre

class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    encuesta_script = models.TextField(blank=True, null=True)  # Campo para el script

    def __str__(self):
        return self.user.username