# Generated by Django 4.2.16 on 2024-11-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_cliente_producto_alter_cliente_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="empresa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
