# Generated by Django 4.2.16 on 2024-11-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_cliente_estado_cliente_fecha_in_cliente_fecha_sal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nuevo", "Nuevo"),
                    ("Proceso", "Proceso"),
                    ("Contactado", "Contactado"),
                    ("Laboratorio", "Laboratorio"),
                    ("Trabajo", "Trabajo"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="sucursal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Barranquilla", "Barranquilla"),
                    ("Bucaramanga", "Bucaramanga"),
                    ("Cali", "Cali"),
                    ("Centro", "Centro"),
                    ("Chapinero", "Chapinero"),
                    ("Chía", "Chía"),
                    ("Cúcuta", "Cúcuta"),
                    ("Deposito", "Deposito"),
                    ("Manizales", "Manizales"),
                    ("Medellín", "Medellín"),
                    ("Neiva", "Neiva"),
                    ("Olaya", "Olaya"),
                    ("Pereira", "Pereira"),
                    ("Pincipal", "Pincipal"),
                    ("PteAranda", "PteAranda"),
                    ("Rio Negro", "Rio Negro"),
                    ("Tunja", "Tunja"),
                ],
                max_length=32,
            ),
        ),
    ]
