# Generated by Django 4.0.6 on 2025-05-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_perfilusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='operario',
            new_name='asesor',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_sal',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='producto',
            field=models.CharField(max_length=255),
        ),
    ]
